Mini_Ecommerce_Comsuming_APIS/Controllers/LayoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Mini_Ecommerce_Comsuming_APIS.Controllers
{
    public class LayoutController : Controller
    {
        public IActionResult Darkly()
        {
            string key = "Keyvalue";
            string value = "Darkly";
            if (Request.Cookies["Keyvalue"] != null)
            {
                Response.Cookies.Append(key, value);
            }
            return RedirectToAction("Index", "Product");
        }
        public IActionResult Cerulean()
        {
            string key = "Keyvalue";
            string value = "Cerulean";
            if (Request.Cookies["Keyvalue"] != null)
            {
                Response.Cookies.Append(key, value);
            }
            return RedirectToAction("Index", "Product");
        }

    }
}

Mini_Ecommerce_Comsuming_APIS/Views/Shared/_DarklyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mini_Ecommerce_Comsuming_APIS</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css//bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/darkly.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand font-monospace font-bold" href="#"> <i class="bi bi-cart-check"></i>&nbsp;MINIECOMMERCE |</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">

                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                                <ul class="navbar-nav flex-grow-1">

                                    <li class="nav-item">
                                        <a class="nav-link font-bold" asp-area="" asp-controller="Product" asp-action="Index">HOME</a>
                                    </li>
                                    <li class="nav-item d-flex">
                                        <a class="nav-link font-bold" asp-area="" asp-controller="Product" asp-action="Add">CREATE</a>
                                    </li>
                                </ul>
                                <li>
                                    <input class="form-control form-control-lg" type="text" placeholder="Search Product" id="SearchBar">
                                </li>
                                <span>
                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                </span>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Theme
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li>
                                            <a class="nav-link" asp-area="" asp-controller="Layout" asp-action="Darkly">Dark</a>
                                        </li>
                                        <div class="dropdown-divider"></div>
                                        <li>
                                            <a class="nav-link" asp-area="" asp-controller="Layout" asp-action="Cerulean">Light</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Account
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li class="nav-item">
                                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout"> <i class="bi bi-person-x-fill"></i>&nbsp;Logout</a>
                                        </li>
                                    </ul>
                                </li>
                                <span>
                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                </span>
                                <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Cart"><i class="bi bi-cart4"></i></a>
                        }
                        else
                        {
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link font-bold" asp-area="" asp-controller="Product" asp-action="Index">HOME </a>
                                    </li>
                                </ul>
                                <li>
                                    <input class="form-control form-control-lg" type="text" placeholder="Search Product" id="SearchBar">
                                </li>
                                <span>
                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                </span>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Theme
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li>
                                            <a class="nav-link" asp-area="" asp-controller="Layout" asp-action="Darkly">Dark</a>
                                        </li>
                                        <div class="dropdown-divider"></div>
                                        <li>
                                            <a class="nav-link" asp-area="" asp-controller="Layout" asp-action="Cerulean">Light</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Account
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li class="nav-item">
                                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login"><i class="bi bi-person"></i>&nbsp;Login</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register"><i class="bi bi-people"></i> Register</a>
                                        </li>

                                    </ul>
                                </li>
                                <span>
                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                </span>
                                <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Cart"><i class="bi bi-cart4"></i></a>
                        }
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script type="text/javascript" src="~/js/jquery-3.6.0.js"></script>
    <script src="~/js/bootstrap.bundle.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/js/jquery.ez-plus.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mini_Ecommerce_Comsuming_APIS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mini_Ecommerce_Comsuming_APIS</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css//bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/cerulean.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand font-monospace font-bold" href="#"> <i class="bi bi-cart-check"></i>&nbsp;MINIECOMMERCE |</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">

                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <ul class="navbar-nav flex-grow-1">

                                <li class="nav-item">
                                    <a class="nav-link font-bold" asp-area="" asp-controller="Product" asp-action="Index">HOME</a>
                                </li>
                                <li class="nav-item d-flex">
                                    <a class="nav-link font-bold" asp-area="" asp-controller="Product" asp-action="Add">CREATE</a>
                                </li>
                            </ul>
                            <li>
                                <input class="form-control form-control-lg" type="text" placeholder="Search Product" id="SearchBar">
                            </li>
                            <span>
                                &nbsp;
                                &nbsp;
                                &nbsp;
                            </span>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Theme
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Layout" asp-action="Darkly">Dark</a>
                                    </li>
                                    <div class="dropdown-divider"></div>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Layout" asp-action="Cerulean">Light</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Account
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout"> <i class="bi bi-person-x-fill"></i>&nbsp;Logout</a>
                                    </li>

                                </ul>
                            </li>
                            <span>
                                &nbsp;
                                &nbsp;
                                &nbsp;
                                &nbsp;
                            </span>

                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Cart"><i class="bi bi-cart4"></i></a>
                        }
                        else
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link font-bold" asp-area="" asp-controller="Product" asp-action="Index">HOME </a>
                                </li>
                            </ul>
                            <li>
                                <input class="form-control form-control-lg" type="text" placeholder="Search Product" id="SearchBar">
                            </li>
                            <span>
                                &nbsp;
                                &nbsp;
                            </span>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Theme
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Layout" asp-action="Darkly">Dark</a>
                                    </li>
                                    <div class="dropdown-divider"></div>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Layout" asp-action="Cerulean">Light</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Account
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><i class="bi bi-person"></i>&nbsp;Login</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register"><i class="bi bi-people"></i> Register</a>
                                    </li>

                                </ul>
                            </li>
                            <span>
                                &nbsp;
                                &nbsp;
                                &nbsp;
                                &nbsp;
                            </span>
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Cart"><i class="bi bi-cart4"></i></a>
                        }
                    </ul>


                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script type="text/javascript" src="~/js/jquery-3.6.0.js"></script>
    <script src="~/js/bootstrap.bundle.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/js/jquery.ez-plus.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>